Add multipart array test method
nuwave/lighthouse pull request #1615
Opened 2020-11-19 12:45 UTC by jandrodev

- [x] Added or updated tests
- [ ] Documented user facing changes
- [ ] Updated CHANGELOG.md

When it comes to testing mutations with files using the multipartGraphQL method, it is quite tedious to work with json (especially when formatting and viewing the different operations and map blocks). That is why it becomes easier to work with arrays. Under the hood, the operation is the same, but at the time of writing the test it changes a bit to, in my opinion, make it more understandable.

I add the base method and 3 tests to check its operation in which you can see the idea that I comment. If you like, I would need to add the corresponding part in the documentation.

No breaking changes.

2020-11-19 13:58 UTC, spawnia requested changes
I don't want to have two methods to do the same thing. Yours seems better - working with arrays is indeed more pleasant than JSON - so it should replace the previous one.

Given we are working towards a new major version, such breakage is fine. You can prove that your method holds up by converting existing uses of the old multipart method.

2020-11-19 13:58 UTC, spawnia commented on src/Testing/MakesGraphQLRequests.php
> +     * very large or contain many files, it becomes much easier to work with array instead of json.
```suggestion
     * Send a multipart form request to GraphQL.
```

I agree with what is written, but prefer to let the usefulness of the method speak for itself ;)

An actual usage example would be more useful.

2020-11-19 13:58 UTC, spawnia commented on src/Testing/MakesGraphQLRequests.php
> +     * @param array<int, string> $map
```suggestion
     * @param array<string, string> $map
```

2020-11-19 13:58 UTC, spawnia commented on src/Testing/MakesGraphQLRequests.php
> +     * @param array<string, mixed> $operations
```suggestion
     * @param array<string, mixed>|array<int, array<string, mixed>> $operations
```

2020-11-19 14:23 UTC, jandrodev commented
Perfect, so I modify the old method with the new idea.

2020-11-20 12:57 UTC, spawnia commented on src/Testing/MakesGraphQLRequests.php
> +     * @param  array<int, array>  $map
```suggestion
     * @param  array<string, array<int, string>>  $map
```

Integer keys are erased by `json_encode`, which is why all examples use quoted numbers `'0'`. The values are indeed an array (to be precise: a list of strings), good catch.

2020-11-20 13:14 UTC, spawnia commented
Looks like PHP is screwing us with inconsistent behaviour:

```
>>> json_encode(['0' => 4])
=> "[4]"
>>> json_encode(['1' => 4])
=> "{"1":4}"
```

2020-11-20 13:25 UTC, jandrodev commented
Yes, it seems so. The previous annotation might be more correct (or at least it gave less problems hehe). What do you think?

2020-11-20 16:07 UTC, spawnia commented
I noticed that using integer keys also works fine, so I changed the annotation to be more flexible,

2020-11-20 16:09 UTC, spawnia approved these changes
Good idea and well done, thank you

2020-11-20 16:10 UTC, merged

2020-11-20 20:15 UTC, jandrodev commented
😊 👍