Request information in manipulate result
nuwave/lighthouse pull request #1720
Opened 2021-02-03 13:50 UTC by MaartenStaa

- [x] Added or updated tests
- [x] Documented user facing changes *(N/A?)*
- [x] Updated CHANGELOG.md

**Changes**

This adds a query field to the `ManipulateResult` event, so event listeners can know which query to manipulate the result for. We're using [a plugin that sends tracing to Apollo Studio](https://github.com/brightalley/lighthouse-apollo), which for Lighthouse v4 fetches the GraphQL request singleton, but for v5 that no longer exists.

**Breaking changes**

I guess technically it could be considered a breaking change that you now need to pass a second parameter to instantiate a `ManipulateResult`, though I imagine that's not really a typical use case. Let me know if you want me to add this to the breaking changes.

2021-02-03 14:30 UTC, spawnia requested changes

2021-02-03 14:30 UTC, spawnia commented on src/GraphQL.php
> +            new ManipulateResult($result, $query)
Just the query string without the operation name is ambigious, there might be multiple operations in there.

2021-02-03 14:30 UTC, spawnia commented on src/Events/ManipulateResult.php
> +    public function __construct(ExecutionResult &$result, $query)
We should monomorphize that type.

2021-02-03 14:32 UTC, spawnia commented
We can use https://github.com/webonyx/graphql-php/pull/755 once it lands to grab the `OperationDefinitionNode` for the fitting operation.

2021-02-18 21:59 UTC, spawnia commented
I am enhancing the lifecycle events in https://github.com/nuwave/lighthouse/pull/1726, `StartExecution` now holds the executed query. You can grab it off of there.

The reason why I do not want to add the query string to `ManipulateResult` is that this would just create multiple ways of achieving the same thing. I see how it might be convenient for certain users, but a similar argument could then be made for including the query (and the request perhaps) in all other lifecycle events as well.

2021-02-18 21:59 UTC, closed without merging

2021-02-18 22:15 UTC, MaartenStaa commented
@spawnia Maybe I missed some details in scrolling through that PR on my phone, but with the new events how would you able to correlate the query from the `StartExecution` to whatever result object you receive in the `ManipulateResult` or `EndExecution` event?

2021-02-18 23:19 UTC, spawnia commented
The events are guaranteed to arive in order for every executed operation. Your listener will have to be stateful and keep track of the last seen `StartExecution` event when receiving `ManipulateResult`.