Update EnsureXHR to allow X-Requested-With header
nuwave/lighthouse pull request #2221
Opened 2022-10-30 05:05 UTC by eNzyOfficial

- [*] Added or updated tests
- [ ] Documented user facing changes
- [ ] Updated CHANGELOG.md

Resolves #2206

**Changes**

Wrap current logic with an `if` statement to check if header `X-Requested-With` is passed with value `XMLHttpRequest`

**Breaking changes**

Shouldn't break any of the current logic.

2022-10-30 05:07 UTC, eNzyOfficial commented
Still needs the documentation to be updated, not sure the best description to add to `csrf.md`. Let me know what you think should be written and I'll update the PR.

2022-10-31 08:44 UTC, spawnia requested changes

2022-10-31 08:44 UTC, spawnia commented on src/Support/Http/Middleware/EnsureXHR.php
> +        if ($request->header('X-Requested-With', '') !== 'XMLHttpRequest') {
We can avoid nesting by returning early here.

2022-10-31 08:55 UTC, spawnia commented
For https://lighthouse-php.com/master/security/csrf.html:

```markdown
It forbids:
- `GET` requests
- `POST` requests that can be created using HTML forms

It allows:
- other request methods
- `POST` requests with the header `X-Requested-With: XMLHttpRequest`
- `POST` requests with a `Content-Type` that can not be set from HTML forms
```

For https://lighthouse-php.com/master/digging-deeper/file-uploads.html#client-side-usage:

```markdown
> If you are using [the EnsureXHR middleware to protect against CSRF](../security/csrf.md),
> add the header `X-Requested-With: XMLHttpRequest` to your request.
```

2022-11-01 04:57 UTC, eNzyOfficial commented
Requested changes have been made

2022-11-01 11:33 UTC, merged