Added Support to Generate Tests when Generating Field Class
nuwave/lighthouse pull request #2419
Opened 2023-07-03 00:11 UTC by yondifon

- Support Creating Matching Tests in FieldGenerator
- Changelog

 
- [ ] Added or updated tests
- [ ] Documented user facing changes
- [ ] Updated CHANGELOG.md

**Changes**

**Breaking changes**

2023-07-03 00:15 UTC, yondifon commented
I didn't see any tests for https://github.com/nuwave/lighthouse/blob/master/src/Console/FieldGeneratorCommand.php

I didn't know how to approach it. Any ideas ? @spawnia 

(Sorry for tagging you - I apologize for the noise)

2023-07-03 12:34 UTC, spawnia requested changes
Thanks for adding this. There are no tests for this command, but feel free to add some.

2023-07-03 12:34 UTC, spawnia commented on src/Console/stubs/test.stub
> +    public function it_can_use_dummy_field(): void
```suggestion
    public function test_dummy_field(): void
```

2023-07-03 12:34 UTC, spawnia commented on src/Console/stubs/test.stub
> +class DummyClass extends TestCase
```suggestion
final class DummyClass extends TestCase
```

2023-07-03 12:34 UTC, spawnia commented on src/Console/FieldGeneratorCommand.php
> +        $fielName = $name->afterLast('/');
typo

2023-07-03 12:34 UTC, spawnia commented on src/Console/stubs/test.stub
> +            dummyType DummyField {
```suggestion
            maybeMutation{
```

2023-07-03 12:34 UTC, spawnia commented on src/Console/stubs/test.stub
> +            dummyType DummyField {
Let's replace this with either `'mutation '` or `''` for queries.

2023-07-03 12:34 UTC, spawnia commented on src/Console/stubs/test.stub
> +        ]);
```suggestion
        ')->assertJson([
            'data' => [
                // TODO define expected data
                'dummyField' => null,
            ],
        ]);
```

2023-07-03 12:34 UTC, spawnia commented on src/Console/FieldGeneratorCommand.php
> +        if (! $this->option('test') && ! $this->option('pest')) {
This only works with `'test'`, we should either implement `pest` support or warn that it does not work.

2023-07-04 10:08 UTC, yondifon commented
![image](https://github.com/nuwave/lighthouse/assets/35140079/5a7ca9cb-9b96-446a-973a-e3ccdc0a8963)

Couldn't figure out tests.
Sounds Horrible.  I know. 

There are no tests in the Laravel Framework Repo on Generator Class.

2023-07-04 13:41 UTC, spawnia approved these changes
@yondifon please re-review the changes I made.

2023-07-08 22:23 UTC, yondifon commented on src/Console/FieldGeneratorCommand.php
> +            ->replace('dummyField', $operationAndFieldName->afterLast('/')->toString())
Just pushed one last fix. 👍🏾

2023-07-10 07:50 UTC, spawnia approved these changes

2023-07-10 09:04 UTC, merged

2023-07-10 09:05 UTC, spawnia commented
Thank you, released with https://github.com/nuwave/lighthouse/releases/tag/v6.14.0.