v6.37.1 Nested Mutation Regression
nuwave/lighthouse pull request #2591
Opened 2024-07-20 12:24 UTC by Carlwirkus

Here is a draft PR with a test showing the regression from `v6.37.1`. I'll try to reproduce the issue without introducing new models

2024-07-20 12:25 UTC, Carlwirkus commented on tests/Integration/Execution/MutationExecutor/MorphOneTest.php
> +    {
This test passes. I think the issue is related to updating existing models.

2024-07-21 20:50 UTC, spawnia requested changes

2024-07-21 20:50 UTC, spawnia commented on tests/Integration/Execution/MutationExecutor/HasManyTest.php
> +
```suggestion

```

2024-07-21 20:50 UTC, spawnia commented on tests/Integration/Execution/MutationExecutor/HasManyTest.php
> +        assert($user instanceof User);
```suggestion
        assert($user instanceof User);
```

2024-07-21 20:50 UTC, spawnia commented on tests/Integration/Execution/MutationExecutor/HasManyTest.php
> +            mutation UpdateUser($input: UpdateUserInput!){
```suggestion
            mutation ($input: UpdateUserInput!) {
```

2024-07-21 20:50 UTC, spawnia commented on tests/Integration/Execution/MutationExecutor/MorphOneTest.php
> +        mutation UpdateTask($input: UpdateTaskInput!){
```suggestion
        mutation ($input: UpdateTaskInput!) {
```

2024-07-21 22:16 UTC, Carlwirkus commented on tests/Integration/Execution/MutationExecutor/HasManyTest.php
> +
done

2024-07-21 22:16 UTC, Carlwirkus commented on tests/Integration/Execution/MutationExecutor/HasManyTest.php
> +        assert($user instanceof User);
done

2024-07-21 22:16 UTC, Carlwirkus commented on tests/Integration/Execution/MutationExecutor/MorphOneTest.php
> +        mutation UpdateTask($input: UpdateTaskInput!){
done

2024-07-21 22:19 UTC, Carlwirkus commented on tests/Integration/Execution/MutationExecutor/HasManyTest.php
> +            mutation UpdateUser($input: UpdateUserInput!){
done

2024-08-05 17:35 UTC, merged