Force `int` cast on ModelsLoader count
nuwave/lighthouse pull request #2646
Opened 2024-12-28 14:47 UTC by robsontenorio

When dealing with **legacy databases**  the count for this related model returns a string like `"88"`, not `88`.

```
comments: [Comment] @hasMany(type: PAGINATOR)
```

After upgrading to PHP 8.4 this does not work anymore. And it throws a error 

_"Nuwave\Lighthouse\Execution\ModelsLoader\CountModelsLoader::extractCount(): Return value must be of type int, string returned"_

**Changes**

Always cast to integer. Because, this count must be an integer, always.

**Breaking changes**

No.

 
- [ ] Added or updated tests
- [ ] Documented user facing changes
- [ ] Updated CHANGELOG.md

**Changes**

**Breaking changes**

2025-01-03 13:44 UTC, spawnia requested changes

2025-01-03 13:44 UTC, spawnia commented on src/Execution/ModelsLoader/CountModelsLoader.php
>          return $count;
```suggestion
        $count = $model->getAttribute($countAttributeName);
        if (! is_numeric($count)) {
            $nonNumericCount = Utils::printSafe($count);
            throw new \Exception('Expected numeric count, got: {$nonNumericCount}.");
        }

        return (int) $count;
```

I am always wary of unchecked casts, since PHP will do the most senseless cast and just give a wrong result instead of throwing.

2025-01-03 21:09 UTC, robsontenorio commented
@spawnia your  suggested approach didn’t work. 

I also fixed the quote issue, but no luck.

2025-01-03 22:16 UTC, spawnia commented
How is it not working? It is still casting to int.

2025-01-03 23:41 UTC, robsontenorio commented
@spawnia the pipeline is failing :(

2025-01-08 00:22 UTC, robsontenorio commented
@spawnia i forced an dummy commit but I don’t get what is wrong with GitHub actions. Now phpstan complains about other things.

2025-01-08 12:55 UTC, merged

2025-01-08 13:19 UTC, spawnia commented
Released with https://github.com/nuwave/lighthouse/releases/tag/v6.47.1, thank you @robsontenorio